# Generated by Django 5.1.4 on 2024-12-26 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('user', models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='infirmier_app', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Laborantin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='laborantin_app', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laborantin',
                'verbose_name_plural': 'Laborantins',
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medecin_app', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('nss', models.BigIntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(default='Unknown', max_length=200)),
                ('num_telephone', models.BigIntegerField(default='Unknown', unique=True)),
                ('mutuelle', models.IntegerField(default='Unknown')),
                ('medecin_trataint', models.CharField(default='Unknown', max_length=100)),
                ('num_personne_a_contacter', models.BigIntegerField(default='Unknown')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=1)),
                ('user', models.OneToOneField(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='patient_app', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Radiologue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('user', models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='radiologue_app', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('user', models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='technicien_app', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
