# Generated by Django 5.1.4 on 2024-12-27 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField()),
                ('num_securite_sociale', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='infirmier',
            name='password',
        ),
        migrations.RemoveField(
            model_name='laborantin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='radiologue',
            name='password',
        ),
        migrations.AddField(
            model_name='infirmier',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laborantin',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medecin',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiologue',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('resume', models.TextField()),
                ('medecin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medecin')),
                ('dossier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dossierpatient')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duree', models.CharField(max_length=50)),
                ('consultation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.TextField()),
                ('description', models.TextField()),
                ('observation', models.TextField()),
                ('dossier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dossierpatient')),
                ('infirmier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.infirmier')),
            ],
        ),
    ]
