# Generated by Django 5.1.4 on 2024-12-28 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dossierpatient_remove_infirmier_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('voie_administration', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='soin',
            name='dossier_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='soin',
            name='infirmier_id',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_declaration', models.DateField()),
                ('dossier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dossierpatient')),
            ],
        ),
        migrations.CreateModel(
            name='CertificatMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateField()),
                ('motif', models.CharField(max_length=255)),
                ('date_arret', models.CharField(max_length=50)),
                ('dossier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dossierpatient')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('resultat', models.TextField()),
                ('consultation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('contenu', models.TextField()),
                ('auteur_id', models.CharField(max_length=50)),
                ('examen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.examen')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametres', models.TextField()),
                ('valeurs', models.TextField()),
                ('graphique_tendance', models.TextField()),
                ('examen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.examen')),
                ('laborantin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.laborantin')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenRadiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_image', models.CharField(max_length=50)),
                ('fichier_image', models.TextField()),
                ('compte_rendu', models.TextField()),
                ('examen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.examen')),
                ('radiologue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.radiologue')),
            ],
        ),
        migrations.CreateModel(
            name='OrdonnanceMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicament')),
                ('ordonnance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ordonnance')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
