# Generated by Django 5.1.4 on 2024-12-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_medicament_alter_soin_dossier_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedent',
            name='dossier_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='certificatmedical',
            name='dossier_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='compterendu',
            name='examen_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='dossier_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='medecin_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='examen',
            name='consultation_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='examenbiologique',
            name='examen_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='examenbiologique',
            name='laborantin_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='examenradiologique',
            name='examen_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='examenradiologique',
            name='radiologue_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='consultation_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordonnancemedicament',
            name='medicament_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordonnancemedicament',
            name='ordonnance_id',
            field=models.CharField(max_length=50),
        ),
    ]
